#! /usr/bin/python3
import argparse
import argcomplete

from dds_scripts_utils import dds_message, dds_project, dds_workspace, dds_launch, dds_export, version


def getDDSArgs():
    parser = argparse.ArgumentParser(description=f"DDS argument parser ({version.__version__})")
    
    sp = parser.add_subparsers(dest="subcommand", help="subcommand")
    sp_message = sp.add_parser("message", help="process message(create/delete head and source file from xml)", description=f"DDS message argument parser ({version.__version__})")
    dds_message.get_msg_args(sp_message)
    sp_project = sp.add_parser("project", help="process project(create/compile/delete project)", description=f"DDS project argument parser ({version.__version__})")
    dds_project.get_project_args(sp_project)
    sp_workspace = sp.add_parser("workspace", help="process workspace(init/update workspace)", description=f"DDS workspace argument parser ({version.__version__})")
    dds_workspace.get_workspace_args(sp_workspace)
    sp_launch = sp.add_parser("launch", help="launch workspace via launch yaml config", description=f"DDS launch argument parser ({version.__version__})")
    dds_launch.get_launch_args(sp_launch)
    sp_export = sp.add_parser("export", help="export workspace", description=f"DDS export argument parser ({version.__version__})")
    dds_export.get_export_args(sp_export)
    
    argcomplete.autocomplete(parser)
    
    return parser.parse_args()


if __name__ == "__main__":
    args = getDDSArgs()
    # print(args)
    cmd = args.subcommand
    getattr(eval(f"dds_{cmd}"), f"do_{cmd}_process")(args)
